name: PistonMOTD
version: ${parent.version}
api-version: 1.13
main: net.pistonmaster.pistonmotd.bukkit.PistonMOTDBukkit
description: ${parent.description}
website: ${parent.url}
softdepend: [ "LuckPerms" ]
commands:
  pistonmotd:
    description: Allows you to execute some commands for pistonmotd.
    permission: pistonmotd.command
    aliases: [ "pistonmotdbukkit" ]

permissions:
  pistonmotd.help:
    description: Permission to have the help menu shown.
    default: op
    children:
      - pistonmotd.command
  pistonmotd.reload:
    description: Permission to reload the motd config.
    default: op
    children:
      - pistonmotd.command
  pistonmotd.command:
    description: Permission to even access the cmd.
    default: op